// Compact IATA airport lookup for the flight editor: type a code and the
// name + timezone fill themselves. Offline, no API. Codes not listed simply
// don't autofill — the user keeps typing as before.

export interface AirportInfo { name: string; tz: string }

export const AIRPORTS: Record<string, AirportInfo> = {
  // ── Thailand ──
  BKK: { name: 'Suvarnabhumi Airport', tz: 'Asia/Bangkok' },
  DMK: { name: 'Don Mueang Intl Airport', tz: 'Asia/Bangkok' },
  CNX: { name: 'Chiang Mai Intl Airport', tz: 'Asia/Bangkok' },
  CEI: { name: 'Chiang Rai Intl Airport', tz: 'Asia/Bangkok' },
  HKT: { name: 'Phuket Intl Airport', tz: 'Asia/Bangkok' },
  HDY: { name: 'Hat Yai Intl Airport', tz: 'Asia/Bangkok' },
  KBV: { name: 'Krabi Intl Airport', tz: 'Asia/Bangkok' },
  USM: { name: 'Samui Airport', tz: 'Asia/Bangkok' },
  UTH: { name: 'Udon Thani Airport', tz: 'Asia/Bangkok' },
  UBP: { name: 'Ubon Ratchathani Airport', tz: 'Asia/Bangkok' },
  KKC: { name: 'Khon Kaen Airport', tz: 'Asia/Bangkok' },
  // ── Hong Kong / Macau / Taiwan ──
  HKG: { name: 'Hong Kong Intl Airport', tz: 'Asia/Hong_Kong' },
  MFM: { name: 'Macau Intl Airport', tz: 'Asia/Macau' },
  TPE: { name: 'Taoyuan Intl Airport', tz: 'Asia/Taipei' },
  TSA: { name: 'Taipei Songshan Airport', tz: 'Asia/Taipei' },
  KHH: { name: 'Kaohsiung Intl Airport', tz: 'Asia/Taipei' },
  // ── China ──
  PVG: { name: 'Shanghai Pudong Intl Airport', tz: 'Asia/Shanghai' },
  SHA: { name: 'Shanghai Hongqiao Intl Airport', tz: 'Asia/Shanghai' },
  PEK: { name: 'Beijing Capital Intl Airport', tz: 'Asia/Shanghai' },
  PKX: { name: 'Beijing Daxing Intl Airport', tz: 'Asia/Shanghai' },
  CAN: { name: 'Guangzhou Baiyun Intl Airport', tz: 'Asia/Shanghai' },
  SZX: { name: 'Shenzhen Bao’an Intl Airport', tz: 'Asia/Shanghai' },
  TFU: { name: 'Chengdu Tianfu Intl Airport', tz: 'Asia/Shanghai' },
  CTU: { name: 'Chengdu Shuangliu Intl Airport', tz: 'Asia/Shanghai' },
  CKG: { name: 'Chongqing Jiangbei Intl Airport', tz: 'Asia/Shanghai' },
  KMG: { name: 'Kunming Changshui Intl Airport', tz: 'Asia/Shanghai' },
  XIY: { name: 'Xi’an Xianyang Intl Airport', tz: 'Asia/Shanghai' },
  HGH: { name: 'Hangzhou Xiaoshan Intl Airport', tz: 'Asia/Shanghai' },
  NKG: { name: 'Nanjing Lukou Intl Airport', tz: 'Asia/Shanghai' },
  WUH: { name: 'Wuhan Tianhe Intl Airport', tz: 'Asia/Shanghai' },
  XMN: { name: 'Xiamen Gaoqi Intl Airport', tz: 'Asia/Shanghai' },
  FOC: { name: 'Fuzhou Changle Intl Airport', tz: 'Asia/Shanghai' },
  TAO: { name: 'Qingdao Jiaodong Intl Airport', tz: 'Asia/Shanghai' },
  TSN: { name: 'Tianjin Binhai Intl Airport', tz: 'Asia/Shanghai' },
  DLC: { name: 'Dalian Zhoushuizi Intl Airport', tz: 'Asia/Shanghai' },
  HRB: { name: 'Harbin Taiping Intl Airport', tz: 'Asia/Shanghai' },
  SYX: { name: 'Sanya Phoenix Intl Airport', tz: 'Asia/Shanghai' },
  HAK: { name: 'Haikou Meilan Intl Airport', tz: 'Asia/Shanghai' },
  KWL: { name: 'Guilin Liangjiang Intl Airport', tz: 'Asia/Shanghai' },
  LJG: { name: 'Lijiang Sanyi Intl Airport', tz: 'Asia/Shanghai' },
  JHG: { name: 'Xishuangbanna Gasa Airport', tz: 'Asia/Shanghai' },
  CSX: { name: 'Changsha Huanghua Intl Airport', tz: 'Asia/Shanghai' },
  // ── Japan ──
  NRT: { name: 'Narita Intl Airport', tz: 'Asia/Tokyo' },
  HND: { name: 'Tokyo Haneda Airport', tz: 'Asia/Tokyo' },
  KIX: { name: 'Kansai Intl Airport', tz: 'Asia/Tokyo' },
  ITM: { name: 'Osaka Itami Airport', tz: 'Asia/Tokyo' },
  NGO: { name: 'Chubu Centrair Intl Airport', tz: 'Asia/Tokyo' },
  FUK: { name: 'Fukuoka Airport', tz: 'Asia/Tokyo' },
  CTS: { name: 'New Chitose Airport', tz: 'Asia/Tokyo' },
  OKA: { name: 'Naha Airport', tz: 'Asia/Tokyo' },
  SDJ: { name: 'Sendai Airport', tz: 'Asia/Tokyo' },
  KOJ: { name: 'Kagoshima Airport', tz: 'Asia/Tokyo' },
  // ── Korea ──
  ICN: { name: 'Incheon Intl Airport', tz: 'Asia/Seoul' },
  GMP: { name: 'Gimpo Intl Airport', tz: 'Asia/Seoul' },
  PUS: { name: 'Gimhae Intl Airport (Busan)', tz: 'Asia/Seoul' },
  CJU: { name: 'Jeju Intl Airport', tz: 'Asia/Seoul' },
  // ── Southeast Asia ──
  SIN: { name: 'Singapore Changi Airport', tz: 'Asia/Singapore' },
  KUL: { name: 'Kuala Lumpur Intl Airport', tz: 'Asia/Kuala_Lumpur' },
  PEN: { name: 'Penang Intl Airport', tz: 'Asia/Kuala_Lumpur' },
  LGK: { name: 'Langkawi Intl Airport', tz: 'Asia/Kuala_Lumpur' },
  BKI: { name: 'Kota Kinabalu Intl Airport', tz: 'Asia/Kuching' },
  CGK: { name: 'Soekarno-Hatta Intl Airport', tz: 'Asia/Jakarta' },
  DPS: { name: 'Ngurah Rai Intl Airport (Bali)', tz: 'Asia/Makassar' },
  SUB: { name: 'Juanda Intl Airport (Surabaya)', tz: 'Asia/Jakarta' },
  MNL: { name: 'Ninoy Aquino Intl Airport', tz: 'Asia/Manila' },
  CEB: { name: 'Mactan-Cebu Intl Airport', tz: 'Asia/Manila' },
  SGN: { name: 'Tan Son Nhat Intl Airport', tz: 'Asia/Ho_Chi_Minh' },
  HAN: { name: 'Noi Bai Intl Airport', tz: 'Asia/Ho_Chi_Minh' },
  DAD: { name: 'Da Nang Intl Airport', tz: 'Asia/Ho_Chi_Minh' },
  CXR: { name: 'Cam Ranh Intl Airport (Nha Trang)', tz: 'Asia/Ho_Chi_Minh' },
  PQC: { name: 'Phu Quoc Intl Airport', tz: 'Asia/Ho_Chi_Minh' },
  HPH: { name: 'Cat Bi Intl Airport (Hai Phong)', tz: 'Asia/Ho_Chi_Minh' },
  REP: { name: 'Siem Reap-Angkor Intl Airport', tz: 'Asia/Phnom_Penh' },
  PNH: { name: 'Phnom Penh Intl Airport', tz: 'Asia/Phnom_Penh' },
  RGN: { name: 'Yangon Intl Airport', tz: 'Asia/Yangon' },
  MDL: { name: 'Mandalay Intl Airport', tz: 'Asia/Yangon' },
  VTE: { name: 'Wattay Intl Airport (Vientiane)', tz: 'Asia/Vientiane' },
  LPQ: { name: 'Luang Prabang Intl Airport', tz: 'Asia/Vientiane' },
  BWN: { name: 'Brunei Intl Airport', tz: 'Asia/Brunei' },
  // ── South Asia ──
  DEL: { name: 'Indira Gandhi Intl Airport (Delhi)', tz: 'Asia/Kolkata' },
  BOM: { name: 'Chhatrapati Shivaji Intl Airport (Mumbai)', tz: 'Asia/Kolkata' },
  BLR: { name: 'Kempegowda Intl Airport (Bengaluru)', tz: 'Asia/Kolkata' },
  MAA: { name: 'Chennai Intl Airport', tz: 'Asia/Kolkata' },
  CCU: { name: 'Netaji Subhas Chandra Bose Intl Airport', tz: 'Asia/Kolkata' },
  DAC: { name: 'Hazrat Shahjalal Intl Airport (Dhaka)', tz: 'Asia/Dhaka' },
  CMB: { name: 'Bandaranaike Intl Airport (Colombo)', tz: 'Asia/Colombo' },
  KTM: { name: 'Tribhuvan Intl Airport (Kathmandu)', tz: 'Asia/Kathmandu' },
  MLE: { name: 'Velana Intl Airport (Malé)', tz: 'Indian/Maldives' },
  // ── Middle East ──
  DXB: { name: 'Dubai Intl Airport', tz: 'Asia/Dubai' },
  AUH: { name: 'Abu Dhabi Zayed Intl Airport', tz: 'Asia/Dubai' },
  DOH: { name: 'Hamad Intl Airport (Doha)', tz: 'Asia/Qatar' },
  JED: { name: 'King Abdulaziz Intl Airport (Jeddah)', tz: 'Asia/Riyadh' },
  RUH: { name: 'King Khalid Intl Airport (Riyadh)', tz: 'Asia/Riyadh' },
  IST: { name: 'Istanbul Airport', tz: 'Europe/Istanbul' },
  SAW: { name: 'Istanbul Sabiha Gökçen Airport', tz: 'Europe/Istanbul' },
  // ── Europe ──
  LHR: { name: 'London Heathrow Airport', tz: 'Europe/London' },
  LGW: { name: 'London Gatwick Airport', tz: 'Europe/London' },
  MAN: { name: 'Manchester Airport', tz: 'Europe/London' },
  EDI: { name: 'Edinburgh Airport', tz: 'Europe/London' },
  DUB: { name: 'Dublin Airport', tz: 'Europe/Dublin' },
  CDG: { name: 'Paris Charles de Gaulle Airport', tz: 'Europe/Paris' },
  ORY: { name: 'Paris Orly Airport', tz: 'Europe/Paris' },
  NCE: { name: 'Nice Côte d’Azur Airport', tz: 'Europe/Paris' },
  AMS: { name: 'Amsterdam Schiphol Airport', tz: 'Europe/Amsterdam' },
  BRU: { name: 'Brussels Airport', tz: 'Europe/Brussels' },
  FRA: { name: 'Frankfurt Airport', tz: 'Europe/Berlin' },
  MUC: { name: 'Munich Airport', tz: 'Europe/Berlin' },
  BER: { name: 'Berlin Brandenburg Airport', tz: 'Europe/Berlin' },
  ZRH: { name: 'Zurich Airport', tz: 'Europe/Zurich' },
  GVA: { name: 'Geneva Airport', tz: 'Europe/Zurich' },
  VIE: { name: 'Vienna Intl Airport', tz: 'Europe/Vienna' },
  FCO: { name: 'Rome Fiumicino Airport', tz: 'Europe/Rome' },
  MXP: { name: 'Milan Malpensa Airport', tz: 'Europe/Rome' },
  VCE: { name: 'Venice Marco Polo Airport', tz: 'Europe/Rome' },
  NAP: { name: 'Naples Intl Airport', tz: 'Europe/Rome' },
  MAD: { name: 'Madrid-Barajas Airport', tz: 'Europe/Madrid' },
  BCN: { name: 'Barcelona-El Prat Airport', tz: 'Europe/Madrid' },
  LIS: { name: 'Lisbon Humberto Delgado Airport', tz: 'Europe/Lisbon' },
  ATH: { name: 'Athens Intl Airport', tz: 'Europe/Athens' },
  PRG: { name: 'Václav Havel Airport Prague', tz: 'Europe/Prague' },
  BUD: { name: 'Budapest Ferenc Liszt Intl Airport', tz: 'Europe/Budapest' },
  WAW: { name: 'Warsaw Chopin Airport', tz: 'Europe/Warsaw' },
  CPH: { name: 'Copenhagen Airport', tz: 'Europe/Copenhagen' },
  ARN: { name: 'Stockholm Arlanda Airport', tz: 'Europe/Stockholm' },
  OSL: { name: 'Oslo Gardermoen Airport', tz: 'Europe/Oslo' },
  HEL: { name: 'Helsinki-Vantaa Airport', tz: 'Europe/Helsinki' },
  // ── Americas ──
  JFK: { name: 'John F. Kennedy Intl Airport', tz: 'America/New_York' },
  EWR: { name: 'Newark Liberty Intl Airport', tz: 'America/New_York' },
  BOS: { name: 'Boston Logan Intl Airport', tz: 'America/New_York' },
  IAD: { name: 'Washington Dulles Intl Airport', tz: 'America/New_York' },
  ATL: { name: 'Hartsfield-Jackson Atlanta Intl Airport', tz: 'America/New_York' },
  MIA: { name: 'Miami Intl Airport', tz: 'America/New_York' },
  ORD: { name: 'Chicago O’Hare Intl Airport', tz: 'America/Chicago' },
  DFW: { name: 'Dallas/Fort Worth Intl Airport', tz: 'America/Chicago' },
  IAH: { name: 'Houston George Bush Intl Airport', tz: 'America/Chicago' },
  LAX: { name: 'Los Angeles Intl Airport', tz: 'America/Los_Angeles' },
  SFO: { name: 'San Francisco Intl Airport', tz: 'America/Los_Angeles' },
  SAN: { name: 'San Diego Intl Airport', tz: 'America/Los_Angeles' },
  SEA: { name: 'Seattle-Tacoma Intl Airport', tz: 'America/Los_Angeles' },
  LAS: { name: 'Harry Reid Intl Airport (Las Vegas)', tz: 'America/Los_Angeles' },
  HNL: { name: 'Daniel K. Inouye Intl Airport (Honolulu)', tz: 'Pacific/Honolulu' },
  YVR: { name: 'Vancouver Intl Airport', tz: 'America/Vancouver' },
  YYZ: { name: 'Toronto Pearson Intl Airport', tz: 'America/Toronto' },
  YUL: { name: 'Montréal-Trudeau Intl Airport', tz: 'America/Toronto' },
  // ── Oceania / Africa ──
  SYD: { name: 'Sydney Kingsford Smith Airport', tz: 'Australia/Sydney' },
  MEL: { name: 'Melbourne Airport', tz: 'Australia/Melbourne' },
  BNE: { name: 'Brisbane Airport', tz: 'Australia/Brisbane' },
  PER: { name: 'Perth Airport', tz: 'Australia/Perth' },
  AKL: { name: 'Auckland Airport', tz: 'Pacific/Auckland' },
  CHC: { name: 'Christchurch Intl Airport', tz: 'Pacific/Auckland' },
  CAI: { name: 'Cairo Intl Airport', tz: 'Africa/Cairo' },
  JNB: { name: 'O. R. Tambo Intl Airport (Johannesburg)', tz: 'Africa/Johannesburg' },
  CPT: { name: 'Cape Town Intl Airport', tz: 'Africa/Johannesburg' },
  NBO: { name: 'Jomo Kenyatta Intl Airport (Nairobi)', tz: 'Africa/Nairobi' },
  ADD: { name: 'Addis Ababa Bole Intl Airport', tz: 'Africa/Addis_Ababa' },
}

/** Lookup by IATA code (case-insensitive); null when unknown. */
export function airportByCode(code: string | null | undefined): AirportInfo | null {
  if (!code) return null
  return AIRPORTS[code.trim().toUpperCase()] ?? null
}
