// Beijing Subway network (lines, official colours, stations in order) for
// transit suggestions. English only — the source writes each station as
// "Romanised (English) 中文"; the Chinese is dropped and everything else kept,
// so searching either "Guojia Tushuguan" or "National Library" finds it.
// Trams (Xijiao Line, Yizhuang T1) are deliberately not included.
interface BeijingLine { name: string; color: string; stations: string[] }

export const BEIJING: { match: string[]; lines: BeijingLine[] } = {
  match: ['beijing', 'ปักกิ่ง', 'peking', '北京'],
  lines: [
    { name: 'Line 1', color: '#A4343A', stations: ["Pingguoyuan", "Gucheng", "Babaoshan", "Yuquan Lu", "Wukesong", "Wanshou Lu", "Gongzhufen", "Military Museum", "Muxidi", "Nanlishi Lu", "Fuxingmen", "Xidan", "Tian'anmenxi", "Tian'anmendong", "Wangfujing", "Dongdan", "Jianguomen", "Yong'an Li", "Guomao", "Dawang Lu", "Sihui", "Sihui Dong (E)", "Gaobeidian", "Communication Univ. of China", "Shuang Qiao", "Guanzhuang", "Bali Qiao", "Tongzhou Beiyuan", "Guoyuan", "Jiukeshu", "Liyuan", "Linheli", "Tu Qiao", "Huazhuang", "Universal Resort"] },
    { name: 'Line 2', color: '#004B87', stations: ["Xizhimen", "Chegongzhuang", "Fucheng Men", "Fuxingmen", "Changchun Jie", "Xuanwu Men", "Heping Men", "Qianmen", "Chongwen Men", "Beijing Zhan (Beijing Railway Station)", "Jianguomen", "Chaoyang Men", "Dongsi Shitiao", "Dongzhimen", "Yonghegong Lama Temple", "Anding Men", "Gulou Dajie", "Jishuitan"] },
    { name: 'Line 3', color: '#E20035', stations: ["Dongsi Shitiao", "Workers' Stadium", "Tuanjiehu", "Chaoyang Park", "Shifoying", "Chaoyang Railway Station", "Yaojiayuan", "Dongbanan", "Dongba", "Dongbabei"] },
    { name: 'Line 4 / Daxing', color: '#008C95', stations: ["Anheqiao Bei (N)", "Beigongmen", "Xi Yuan", "Yuanmingyuan Park", "Peking Univ. East Gate", "Zhongguancun", "Haidian Huangzhuang", "Renmin Univ.", "Weigongcun", "Guojia Tushuguan (National Library)", "Dongwuyuan (Beijing Zoo)", "Xizhimen", "Xinjie Kou", "Ping'anli", "Xisi", "Lingjing Hutong", "Xidan", "Xuanwu Men", "Caishi Kou", "Taoranting", "Beijingnan Zhan (Beijing South Railway Station)", "Majiapu", "Jiaomen Xi (W)", "Gongyi Xiqiao", "Xingong", "Xihong Men", "Gaomidian Bei (N)", "Gaomidian Nan (S)", "Zaoyuan", "Qingyuan Lu", "Huangcun Xidajie", "Huangcun Railway Station", "Yihezhuang", "Biomedical Base", "Tiangong Yuan"] },
    { name: 'Line 5', color: '#AA0061', stations: ["Tiantongyuan Bei (N)", "Tiantongyuan", "Tiantongyuan Nan (S)", "Lishui Qiao", "Lishuiqiao Nan (S)", "Beiyuanlu Bei (N)", "Datunludong", "Huixin Xijie Beikou", "Huixin Xijie Nankou", "Heping Xiqiao", "Hepingli Beijie", "Yonghegong Lama Temple", "Beixinqiao", "Zhangzizhong Lu", "Dongsi", "Dengshi Kou", "Dongdan", "Chongwen Men", "Ciqi Kou", "Temple of Heaven East Gate", "Puhuangyu", "Liujiayao", "Songjiazhuang"] },
    { name: 'Line 6', color: '#B58500', stations: ["Jin'anqiao", "Pingguoyuan", "Yangzhuang", "Xihuangcun", "Liaogongzhuang", "Tiancun", "Haidian Wuluju", "Cishou Si", "Huayuanqiao", "Baishiqiaonan", "Erligou", "Chegongzhuang Xi (W)", "Chegongzhuang", "Ping'anli", "Beihai Bei (N)", "Nanluogu Xiang", "Dongsi", "Chaoyang Men", "Dongdaqiao", "Hujialou", "Jintai Lu", "Shilipu", "Qingnian Lu", "Dalianpo", "Huangqu", "Changying", "Caofang", "Wuzi Xueyuan Lu", "Tongzhou Beiguan", "Tongyun Men", "Beiyunhe Xi (W)", "Beiyunhe Dong (E)", "Haojia Fu", "Dongxia Yuan", "Lucheng", "Luyang"] },
    { name: 'Line 7', color: '#FFC56E', stations: ["Beijingxi Zhan (Beijing West Railway Station)", "Wanzi", "Daguanying", "Guang'anmen Nei", "Caishi Kou", "Hufangqiao", "Zhushikou", "Qiaowan", "Ciqi Kou", "Guanqumen Nei", "Guangqumen Wai", "Shuangjing", "Jiulongshan", "Dajiaoting", "Baiziwan", "Huagong", "Nanlouzi Zhuang", "Happy Valley", "Fatou", "Shuanghe", "Jiaohua Chang", "Huangchang", "Langxinzhuang", "Heizhuanghu", "Wanshen Xi (W)", "Wansheng Dong (E)", "Qunfang", "Gaoloujin", "Huazhuang", "Universal Resort"] },
    { name: 'Line 8', color: '#009B77', stations: ["Zhuxinzhuang", "Yuzhi Lu", "Pingxi Fu", "Huilongguan Dongdajie", "Huoying", "Yuxin", "Xixiao Kou", "Yongtaizhuang", "Lincuiqiao", "Senlin Gongyuan Nanmen (Forest Park South Gate)", "Aolinpike Gongyuan (Olympic Park)", "Aoti Zhongxin (Olympic Sports Center)", "Beitucheng", "Anhuaqiao", "Andeli Beijie", "Gulou Dajie", "Shichahai", "Nanluogu Xiang", "Zhongguo Meishuguan (National Art Museum)", "Jinyu Hutong", "Wangfujing", "Qianmen", "Zhushikou", "Tianqiao", "Yongdingmenwai", "Muxi Yuan", "Haihutun", "Dahong Men", "Dahongmen Nan (S)", "Heyi", "Donggaodi", "Huojian Wanyuan", "Wufutang", "Demao", "Yinghai"] },
    { name: 'Line 9', color: '#97D700', stations: ["Guojia Tushuguan (National Library)", "Baishiqiaonan", "Baiduizi", "Military Museum", "Beijingxi Zhan (Beijing West Railway Station)", "Liuliqiao Dong (E)", "Liuli Qiao", "Qilizhuang", "Fengtai Dongdajie", "Fengtai Nanlu", "Keyi Lu", "Fengtai Science Park", "Guogongzhuang"] },
    { name: 'Line 10', color: '#0092BC', stations: ["Bagou", "Suzhou Jie", "Haidian Huangzhuang", "Zhichun Li", "Zhichun Lu", "Xitucheng", "Mudanyuan", "Jiande Men", "Beitucheng", "Anzhenmen", "Huixin Xijie Nankou", "Shaoyaoju", "Taiyanggong", "Sanyuan Qiao", "Liangma Qiao", "Agricultural Exhibition Center", "Tuanjiehu", "Hujialou", "Jintai Xizhao", "Guomao", "Shuangjing", "Jingsong", "Panjia Yuan", "Shilihe", "Fenzhong Si", "Chengshou Si", "Songjiazhuang", "Shiliuzhuang", "Dahong Men", "Jiaomen Dong (E)", "Jiaomen Xi (W)", "Caoqiao", "Jijiamiao", "Capital Univ. of Economics & Business", "Fengtai Railway Station", "Niwa", "Xiju", "Liuli Qiao", "Lianhua Qiao", "Gongzhufen", "Xidiaoyutai", "Cishou Si", "Chedaogou", "Changchun Qiao", "Huoqiying"] },
    { name: 'Line 11', color: '#E8617E', stations: ["Moshikou", "Jin'anqiao", "Beixin'an", "Xinshougang (Shougang Park)"] },
    { name: 'Line 12', color: '#8B5A2B', stations: ["Sijiqing Qiao", "Landianchang", "Changchun Qiao", "Suzhou Qiao", "Renmin Univ.", "Dazhong Si", "Jimen Qiao", "Beitaipingzhuang", "Madian Qiao", "Anhuaqiao", "Anzhen Qiao", "Heping Xiqiao", "Guangxi Men", "Xibahe", "Sanyuan Qiao", "Jiangtaixi", "Gaojiayuan", "Tuofangying", "Dongbaxi", "Dongbabei"] },
    { name: 'Line 13', color: '#F4DA40', stations: ["Xizhimen", "Dazhong Si", "Zhichun Lu", "Wudao Kou", "Shangdi", "Qinghe Zhan (Qinghe Railway Station)", "Xi'erqi", "Longze", "Huilong Guan", "Huoying", "Lishui Qiao", "Bei Yuan", "Wangjing Xi (W)", "Shaoyaoju", "Guangxi Men", "Liufang", "Dongzhimen"] },
    { name: 'Line 14', color: '#CA9A8E', stations: ["Zhangguozhuang", "Garden Expo Park", "Dawayao", "Guozhuangzi", "Dajing", "Qilizhuang", "Xiju", "Dongguantou", "Lize Shangwuqu", "Caihuying", "Xitieying", "Jingfengmen", "Beijingnan Zhan (Beijing South Railway Station)", "Yongdingmenwai", "Jingtai", "Puhuangyu", "Fangzhuang", "Shilihe", "Beijing Univ. of Tech. West Gate", "Pingle Yuan", "Jiulongshan", "Dawang Lu", "Jintai Lu", "Chaoyang Park", "Zaoying", "Dongfeng Beiqiao", "Jiangtai", "Wangjing Nan (S)", "Futong", "Wangjing", "Donghuqu", "Laiguangying", "Shangezhuang"] },
    { name: 'Line 15', color: '#653279', stations: ["Fengbo", "Shunyi", "Shimen", "Nanfaxin", "Houshayu", "Hualikan", "China Int'l Exhibition Center", "Sunhe", "Maquanying", "Cuigezhuang", "Wangjing Dong (E)", "Wangjing", "Wangjing Xi (W)", "Guanzhuang", "Datunludong", "Anli Lu", "Aolinpike Gongyuan (Olympic Park)", "Beishatan", "Liudao Kou", "Qinghua Donglu Xikou"] },
    { name: 'Line 16', color: '#6BA539', stations: ["Bei'anhe", "Wenyang Lu", "Daoxianghu Lu", "Tundian", "Yongfeng", "Yongfeng Nan (S)", "Xibeiwang", "Malianwa", "Nongda Nanlu", "Xi Yuan", "Wanquanhe Qiao", "Suzhou Jie", "Suzhou Qiao", "Wanshou Si", "Guojia Tushuguan (National Library)", "Erligou", "Ganjiakou", "Yuyuantan Dongmen (Yuyuantan Park East Gate)", "Muxidi", "Daguanying", "Honglian Nanlu", "Lize Shangwuqu", "Dongguantou Nan (S)", "Fengtai Railway Station", "Fengtai Nanlu", "Fufengqiao", "Kandan", "Yushuzhuang", "Hongtaizhuang", "Wanpingcheng"] },
    { name: 'Line 17', color: '#2E8B57', stations: ["Weilaikexuechengbei (Future Science City North)", "Weilaikexuecheng (Future Science City)", "Tiantongyuandong", "Qingheying", "Hongjunying", "Wangjing Xi (W)", "Taiyanggong", "Xibahe", "Zuojiazhuang", "Workers' Stadium", "Dongdaqiao", "Yong'an Li", "Panjiayuanxi", "Shilihe", "Zhoujiazhuang", "Shibalidian", "Beishenshu", "Ciqubei", "Ciqu", "Jiahuihu"] },
    { name: 'Line 18', color: '#FF8C00', stations: ["Malianwa", "Shangdi Ruanjianyuan", "Dongbeiwang", "Longzexi", "Huilongguan Xidajie", "Wenhualu", "Huilongguan Dongdajie", "Huoyingdong", "Tiantongyuan", "Taipingzhuang", "Tiantongyuandong"] },
    { name: 'Line 19', color: '#C2185B', stations: ["Mudanyuan", "Beitaipingzhuang", "Jishuitan", "Ping'anli", "Taipingqiao", "Niujie", "Jingfengmen", "Caoqiao", "Xinfadi", "Xingong"] },
    { name: 'Yizhuang Line', color: '#D0006F', stations: ["Songjiazhuang", "Xiaocun", "Xiaohong Men", "Jiu Gong", "Yizhuang Qiao", "Yizhuang Culture Park", "Wanyuan Jie", "Rongjing Dongjie", "Rongchang Dongjie", "Tongji Nanlu", "Jinghai Lu", "Ciqu Nan (S)", "Ciqu", "Yizhuang Railway Station"] },
    { name: 'Changping Line', color: '#D986BA', stations: ["Changping Xishankou", "Ming Tombs", "Changping", "Changping Dongguan", "Beishaowa", "Nanshao", "Shahe Univ. Park", "Shahe", "Gonghua Cheng", "Zhuxinzhuang", "Life Science Park", "Xi'erqi", "Qinghe Zhan (Qinghe Railway Station)", "Zhufangbei", "Qinghe Xiaoyingqiao", "Xuezhiyuan", "Liudao Kou", "Xueyuanqiao", "Xitucheng", "Jimen Qiao"] },
    { name: 'Fangshan Line', color: '#D86018', stations: ["Dongguantou Nan (S)", "Capital Univ. of Economics & Business", "Huaxiang Dongqiao", "Baipenyao", "Guogongzhuang", "Dabaotai", "Daotian", "Changyang", "Libafang", "Guangyang Cheng", "Liangxiang Univ. Town North", "Liangxiang Univ. Town", "Liangxiang Univ. Town West", "Liangxiang Nanguan", "Suzhuang", "Yancun Dong (E)"] },
    { name: 'Yanfang Line', color: '#D86018', stations: ["Yancun Dong (E)", "Zicaowu", "Yancun", "Xingcheng", "Dashihe Dong (E)", "Magezhuang", "Raole Fu", "Fangshan Chengguan", "Yanshan"] },
    { name: 'Line S1', color: '#A45A2A', stations: ["Shichang", "Xiaoyuan", "Liyuanzhuang", "Shang'an", "Qiaohuying", "Sidao Qiao", "Jin'anqiao", "Pingguoyuan"] },
    { name: 'Capital Airport Express', color: '#A192B2', stations: ["Beixinqiao", "Dongzhimen", "Sanyuan Qiao", "Terminal 3", "Terminal 2"] },
    { name: 'Daxing Airport Express', color: '#2249A3', stations: ["Caoqiao", "Daxing Xincheng", "Daxing Jichang (Daxing Airport)"] },
  ],
}
