// Shanghai Metro network (lines, stations, official colors) for transit
// suggestions. Maglev Line uses a two-tone (split) color rendered as a CSS
// gradient so swatches show both halves.
interface ShanghaiLine { name: string; color: string; stations: string[] }

export const SHANGHAI: { match: string[]; lines: ShanghaiLine[] } = {
  match: ['shanghai', 'เซี่ยงไฮ้', '上海'],
  lines: [
    { name: 'Line 1', color: '#e31e2e', stations: ["Xinzhuang", "Waihuanlu", "Lianhua Rd.", "Jinjiang Park", "Shanghai South Railway Station", "Caobao Rd.", "Shanghai Indoor Stadium", "Xujiahui", "Hengshan Rd.", "Changshu Rd.", "Shaanxi Rd. (S)", "Site of the First CPC National Congress · South Huangpi Rd.", "People's Square", "Xinzha Rd.", "Hanzhong Rd.", "Shanghai Railway Station (South Square)", "Zhongshan Rd. (N)", "Yanchang Rd.", "Shanghai Circus World", "Wenshui Rd.", "Pengpu Xincun", "Gongkang Rd.", "Tonghe Xincun", "Hulan Rd.", "Gongfu Xincun", "Baoan Hwy.", "Youyi Rd. (W)", "Fujin Rd."] },
    { name: 'Line 2', color: '#8cc23f', stations: ["Panxiang Rd. Shanghai National Accounting Institute", "National Exhibition & Convention Center", "Hongqiao Railway Station", "Hongqiao Airport T2", "Songhong Rd.", "Beixinjing", "Weining Rd.", "Loushanguan Rd.", "Zhongshan Park", "Jiangsu Rd.", "Jing'an Temple", "West Nanjing Rd.", "People's Square", "East Nanjing Rd.", "Lujiazui", "Pudong Rd. (S)", "Century Ave.", "Shanghai Science & Technology Museum", "Century Park", "Longyang Rd.", "Zhangjiang High-Tech Park", "Jinke Rd.", "Guanglan Rd.", "Tangzhen", "Chuangxin Rd. (M)", "Huaxia Rd. (E)", "Chuansha", "Lingkong Rd.", "Yuandong Ave.", "Haitiansan Rd.", "Pudong Airport T 1 & 2"] },
    { name: 'Line 3', color: '#fdd405', stations: ["Shanghai South Railway Station", "Shilong Rd.", "Longcao Rd.", "Caoxi Rd.", "Yishan Rd.", "Hongqiao Rd.", "Yan'an Rd. (W)", "Zhongshan Park", "Jinshajiang Rd.", "Caoyang Rd.", "Zhenping Rd.", "Zhongtan Rd.", "Shanghai Railway Station(North Square)", "Baoshan Rd.", "Dongbaoxing Rd.", "Hongkou Football Stadium", "Chifeng Rd.", "Dabaishu", "Jiangwan Town", "Yingao Rd. (W)", "Changjiang Rd. (S)", "Songfa Rd.", "Zhanghuabang", "Songbin Rd.", "Shuichan Rd.", "Baoyang Rd.", "Youyi Rd.", "Tieli Rd.", "Jiangyang Rd. (N)"] },
    { name: 'Line 4', color: '#442e87', stations: ["Yishan Rd.", "Hongqiao Rd.", "Yan'an Rd. (W)", "Zhongshan Park", "Jinshajiang Rd.", "Caoyang Rd.", "Zhenping Rd.", "Zhongtan Rd.", "Shanghai Railway Station", "Baoshan Rd.", "Hailun Rd.", "Linping Rd.", "Dalian Rd.", "Yangshupu Rd.", "Pudong Ave.", "Century Ave.", "Xiangcheng Rd.", "Lancun Rd.", "Tangqiao", "Nanpu Bridge", "Xizang Rd. (S)", "Luban Rd.", "Damuqiao Rd.", "Dong'an Rd.", "Shanghai Stadium", "Shanghai Indoor Stadium", "Yishan Rd."] },
    { name: 'Line 5', color: '#954c9a', stations: ["Xinzhuang", "Chunshen Rd.", "Yindu Rd.", "Zhuanqiao", "Beiqiao", "Jianchuan Rd.", "Dongchuan Rd.", "Jiangchuan Rd.", "Xidu", "Xiaotang", "Fengpu Ave.", "Huancheng Rd. (E)", "Wangyuan Rd.", "Jinhai Lake", "Fengxian Xincheng", "Jinping Rd.", "Huaning Rd.", "Wenjing Rd.", "Minhang Development Zone"] },
    { name: 'Line 6', color: '#d31b67', stations: ["Oriental Sports Center", "Lingyan Rd. (S)", "Shangnan Rd.", "Huaxia Rd. (W)", "Gaoqing Rd.", "Dongming Rd.", "Gaoke Rd. (W)", "Linyi Xincun", "Shanghai Children's Medical Center", "Lancun Rd.", "Pudian Rd.", "Century Ave.", "Yuanshen Sports Center", "Minsheng Rd.", "Beiyangjing Rd.", "Deping Rd.", "Yunshan Rd.", "Jinqiao Rd.", "Boxing Rd.", "Wulian Rd.", "Jufeng Rd.", "Dongjing Rd.", "Wuzhou Ave.", "Zhouhai Rd.", "Waigaoqiao Free Trade Zone (S)", "Hangjin Rd.", "Waigaoqiao Free Trade Zone (N)", "Gangcheng Rd."] },
    { name: 'Line 7', color: '#eb7024', stations: ["Meilan Lake", "Luonan Xincun", "Panguang Rd.", "Liuhang", "Gucun Park", "Qihua Rd.", "Shanghai University", "Nanchen Rd.", "Shangda Rd.", "Changzhong Rd.", "Dachang Town", "Xingzhi Rd.", "Dahuasan Rd.", "Xincun Rd.", "Langao Rd.", "Zhenping Rd.", "Changshou Rd.", "Changping Rd.", "Jing'an Temple", "Changshu Rd.", "Zhaojiabang Rd.", "Dong'an Rd.", "Longhua Rd. (M)", "Hou Tan", "Changqing Rd.", "Yaohua Rd.", "Yuntai Rd.", "Gaoke Rd. (W)", "Yanggao Rd. (S)", "Jinxiu Rd.", "Fanghua Rd.", "Longyang Rd.", "Huamu Rd."] },
    { name: 'Line 8', color: '#1f93d1', stations: ["Shendu Hwy.", "Lianhang Rd.", "Jiangyue Rd.", "Pujiang Town", "Luheng Rd.", "Lingzhao Xincun", "Oriental Sports Center", "Yangsi", "Chengshan Rd.", "Yaohua Rd.", "China Art Museum", "Xizang Rd. (S)", "Lujiabang Rd.", "Laoximen", "Dashijie", "People's Square", "Qufu Rd.", "Zhongxing Rd.", "Xizang Rd. (N)", "Hongkou Football Stadium", "Quyang Rd.", "Siping Rd.", "Anshan Xincun", "Jiangpu Rd.", "Huangxing Rd.", "Yanji Rd. (M)", "Huangxing Park", "Xiangyin Rd.", "Nenjiang Rd.", "Shiguang Rd."] },
    { name: 'Line 9', color: '#8acaea', stations: ["Shanghai Songjiang Railway Station", "Zuibaichi", "Songjiang Sports Center", "Songjiang Xincheng", "Songjiang University Town", "Dongjing", "Sheshan", "Sijing", "Jiuting", "Zhongchun Rd.", "Qibao", "Xingzhong Rd.", "Hechuan Rd.", "Caohejing Hi-Tech Park", "Guilin Rd.", "Yishan Rd.", "Xujiahui", "Zhaojiabang Rd.", "Jiashan Rd.", "Dapuqiao", "Madang Rd.", "Lujiabang Rd.", "Xiaonanmen", "Shangcheng Rd.", "Century Ave.", "Yanggao Rd. (M)", "Fangdian Rd.", "Lantian Rd.", "Taierzhuang Rd.", "Jinqiao", "Jinji Rd.", "Jinhai Rd.", "Gutang Rd.", "Minlei Rd.", "Caolu"] },
    { name: 'Line 10', color: '#c9b1d2', stations: ["Hangzhong Rd.", "Ziteng Rd.", "Longbai Xincun", "Hongqiao Railway Station", "Hongqiao Airport T2", "Hongqiao Airport T1", "Shanghai Zoo", "Longxi Rd.", "Shuicheng Rd.", "Yili Rd.", "Songyuan Rd.", "Hongqiao Rd.", "Jiao Tong University", "Shanghai Library", "Shaanxi Rd. (S)", "Site of the First CPC National Congress · Xintiandi", "Laoximen", "Yuyuan Garden", "East Nanjing Rd.", "Tiantong Rd.", "Sichuan Rd. (N)", "Hailun Rd.", "Youdian Xincun", "Siping Rd.", "Tongji University", "Guoquan Rd.", "Wujiaochang", "Jiangwan Stadium", "Sanmen Rd.", "Yingao Rd. (E)", "Xin Jiang Wan Cheng", "Guofan Rd.", "Shuangjiang Rd.", "West Gaoqiao", "Gaoqiao", "Gangcheng Rd.", "Jilong Rd."] },
    { name: 'Line 11', color: '#861b2a', stations: ["Huaqiao", "Guangming Rd.", "Zhaofeng Rd.", "Anting", "Shanghai Automobile City", "Changji Rd. (E)", "Shanghai Circuit", "North Jiading", "West Jiading", "Baiyin Rd.", "Jiading Xincheng", "Malu", "Chengxiang Hwy.", "Nanxiang", "Taopu Xincun", "Wuwei Rd.", "Qilianshan Rd.", "Liziyuan", "Shanghai West Railway Station", "Zhenru", "Fengqiao Rd.", "Caoyang Rd.", "Longde Rd.", "Jiangsu Rd.", "Jiao Tong University", "Xujiahui", "Shanghai Swimming Center", "Longhua", "Yunjin Rd.", "Longyao Rd.", "Oriental Sports Center", "Sanlin", "East Sanlin", "Pusan Rd.", "Kangheng Rd.", "Yuqiao", "Luoshan Rd.", "Xiuyan Rd.", "Kangxin Hwy.", "Disney Resort"] },
    { name: 'Line 12', color: '#017b5f', stations: ["Qixin Rd.", "Hongxin Rd.", "Gudai Rd.", "Donglan Rd.", "Hongmei Rd.", "Hongcao Rd.", "Guilin Park", "Caobao Rd.", "Longcao Rd.", "Longhua", "Longhua Rd. (M)", "Damuqiao Rd.", "Jiashan Rd.", "Shaanxi Rd. (S)", "West Nanjing Rd.", "Hanzhong Rd.", "Qufu Rd.", "Tiantong Rd.", "International Cruise Terminal", "Tilanqiao", "Dalian Rd.", "Jiangpu Park", "Ningguo Rd.", "Longchang Rd.", "Aiguo Rd.", "Fuxing Island", "Donglu Rd.", "Jufeng Rd.", "Yanggao Rd. (N)", "Jinjing Rd.", "Shenjiang Rd.", "Jinhai Rd."] },
    { name: 'Line 13', color: '#ea9bbf', stations: ["Jinyun Rd.", "Jinshajiang Rd. (W)", "Fengzhuang", "Qilianshan Rd. (S)", "Zhenbei Rd.", "Daduhe Rd.", "Jinshajiang Rd.", "Longde Rd.", "Wuning Rd.", "Changshou Rd.", "Jiangning Rd.", "Hanzhong Rd.", "Shanghai Natural History Museum", "West Nanjing Rd.", "Huaihai Rd. (M)", "Site of the First CPC National Congress · Xintiandi", "Madang Rd.", "World Expo Museum", "Shibo Ave.", "Changqing Rd.", "Chengshan Rd.", "Dongming Rd.", "Huapeng Rd.", "Xianan Rd.", "Beicai", "Chenchun Rd.", "Lianxi Rd.", "Huaxia Rd. (M)", "Zhongke Rd.", "Xuelin Rd.", "Zhangjiang Rd."] },
    { name: 'Line 14', color: '#5e5f28', stations: ["Fengbang", "Lexiu Rd.", "Lintao Rd.", "Jiayi Rd.", "Dingbian Rd.", "Zhenxin Xincun", "Zhenguang Rd.", "Tongchuan Rd.", "Zhenru", "Zhongning Rd.", "Caoyang Rd.", "Wuning Rd.", "Wuding Rd.", "Jing'an Temple", "Site of the First CPC National Congress · Huangpi Rd. (S)", "Dashijie", "Yuyuan Garden", "Lujiazui", "Pudong Rd. (S)", "Pudong Ave.", "Yuanshen Rd.", "Changyi Rd.", "Xiepu Rd.", "Yunshan Rd.", "Lantian Rd.", "Huangyang Rd.", "Yunshun Rd.", "Pudong Football Stadium", "Jinyue Rd.", "Guiqiao Rd."] },
    { name: 'Line 15', color: '#b5a17b', stations: ["Zizhu Hi-Tech Park", "Yongde Rd.", "Yuanjiang Rd.", "Shuangbai Rd.", "Shujian Rd.", "Jingxi Rd.", "Hongmei Rd. (S)", "Jinghong Rd.", "Zhumei Rd.", "Luoxiu Rd.", "East China University of Science and Technology", "Shanghai South Railway Station", "Guilin Park", "Guilin Rd.", "Wuzhong Rd.", "Yaohong Rd.", "Hongbaoshi Rd.", "Loushanguan Rd.", "Changfeng Park", "Daduhe Rd.", "Meiling Rd. (N)", "Tongchuan Rd.", "Shanghai West Railway Station", "Wuwei Rd. (E)", "Gulang Rd.", "Qi'an Rd.", "Nanda Rd.", "Fengxiang Rd.", "Jinqiu Rd.", "Gucun Park"] },
    { name: 'Line 16', color: '#95d2c0', stations: ["Longyang Rd.", "Huaxia Rd. (M)", "Luoshan Rd.", "East Zhoupu", "He Sha Hang Cheng", "East Hangtou", "Xinchang", "Wild Animal Park", "Huinan", "East Huinan", "Shuyuan", "Lingang Ave.", "Dishui Lake"] },
    { name: 'Line 17', color: '#b7766b', stations: ["Hongqiao Railway Station", "National Exhibitionand Convention Center", "Panlong Rd.", "Xuying Rd.", "Xujingbeicheng", "Jiasong Rd. (M)", "Zhaoxiang", "Huijin Rd.", "Qingpu Xincheng", "Caoying Rd.", "Dianshanhu Ave.", "Zhujiajiao", "Oriental Land", "Xicen"] },
    { name: 'Line 18', color: '#ab8437', stations: ["Hangtou", "Xiasha", "Hetao Rd.", "Shenmei Rd.", "Fanrong Rd.", "Zhoupu", "Kangqiao", "Yuqiao", "Lianxi Rd.", "Beizhong Rd.", "Fangxin Rd.", "Longyang Rd.", "Yingchun Rd.", "Yanggao Rd. (M)", "Minsheng Rd.", "Changyi Rd.", "Danyang Rd.", "Pingliang Rd.", "Jiangpu Park", "Jiangpu Rd.", "Fushun Rd.", "Guoquan Rd.", "Fudan University", "Shanghai University of Finance and Economics", "Yingao Rd.", "Changjiang Rd. (S)", "Tongnan Rd.", "Changjiang Rd. (W)", "Aihui Rd.", "Hulan Rd.", "Kangwen Rd."] },
    { name: 'Maglev Line', color: 'linear-gradient(90deg,#15665b 50%,#d15627 50%)', stations: ["Longyang Rd.", "Pudong International Airport"] },
    { name: 'Pujiang Line', color: '#b6b6b7', stations: ["Shendu Highway", "Sanlu Highway", "Minrui Road", "Puhang Road", "Dongcheng 1st Road", "Huizhen Road"] },
  ],
}
