// Shenzhen Metro network (lines, ordered stations, official colours) for transit
// suggestions + routing, parsed from the supplied station-list docx; colours are
// the official per-line colours from the legend PDF. Line 2 & 8 share a colour
// (through-running corridor); Line 6 Branch is the 6z spur.
interface ShenzhenLine { name: string; color: string; stations: string[] }

export const SHENZHEN: { match: string[]; lines: ShenzhenLine[] } = {
  match: ['shenzhen', 'เซินเจิ้น', '深圳'],
  lines: [
    { name: 'Line 1', color: '#25af58', stations: ["Luohu", "Guomao", "Laojie", "Grand Theater", "Science Museum", "Huaqiang Rd", "Gangxia", "Convention & Exhibition Center", "Shopping Park", "Xiangmihu", "Chegongmiao", "Zhuzilin", "Qiaocheng East", "OCT", "Window of the World", "Baishizhou", "Hi-Tech Park", "Shenzhen University", "Taoyuan", "Daxin", "Liyumen", "Qianhaiwan", "Xin'an", "Bao'an Center", "Bao'an Stadium", "Pingzhou", "Xixiang", "Gushu", "Hourui", "Airport East"] },
    { name: 'Line 2', color: '#bc6037', stations: ["Chiwan", "Shekou Port", "Sea World", "Shuiwan", "Dongjiaotou", "Wanxia", "Haiyue", "Dengliang", "Houhai", "keyuan", "Hongshuwan", "Window of the World", "Qiaocheng North", "Shenkang", "Antuo Hill", "Qiaoxiang", "Xiangmi", "Xiangmei North", "Jingtian", "Lianhua West", "Futian", "Civic Center", "Gangxia North", "Huaqiang North", "Yannan", "Grand Theater", "Hubei", "Huangbeiling", "Xinxiu", "Liantang Checkpoint", "Xianhu Rd", "Liantang"] },
    { name: 'Line 3', color: '#1ca7e0', stations: ["Futian Bonded Area", "Yitian", "Shixia", "Shopping Park", "Futian", "Children's Palace", "Lianhuacun", "Huaxin", "Tongxinling", "Hongling", "Laojie", "Shaibu", "Cuizhu", "Tianbei", "Shuibei", "Caopu", "Buji", "Mumianwan", "Dafen", "Danzhutou", "Liuyue", "Tangkeng", "Henggang", "Youghu", "He'ao", "Universiade", "Ailian", "Jixiang", "Longcheng Square", "Nanlian", "Shuanglong"] },
    { name: 'Line 4', color: '#e93430', stations: ["Futian Checkpoint", "Fumin", "Convention & Exhibition Center", "Civic Center", "Children's Palace", "Lianhua North", "Shangmeilin", "Minle", "Baishilong", "Shenzhen North Station", "Hongshan", "Shangtang", "Longsheng", "Longhua", "Qinghu"] },
    { name: 'Line 5', color: '#945b9a', stations: ["Chiwan", "Liwan", "Railway Park", "Mawan", "Qianwan Park", "Qianwan", "Guiwan", "Qianhaiwan", "Linhai", "Baohua", "Bao'an Center", "Fanshen", "Lingzhi", "Honglang North", "Xingdong", "Liuxiandong", "Xili", "University Town", "Tanglang", "Changlingpi", "Shenzhen North Station", "Minzhi", "Wuhe", "Bantian", "Yangmei", "Shangshuijing", "Xiashuijing", "Changlong", "Buji", "Baigelong", "Buxin", "Tai'an", "Yijing", "Huangbeiling"] },
    { name: 'Line 6', color: '#1f8e87', stations: ["Science Museum", "Tongxinling", "Sports Center", "Bagualing", "Yinhu", "Hanling", "Meilinguan", "Shenzhen North  Station", "Hongshan", "Shangfen", "Yuanfen", "Yangtai Mountain East", "Guantian", "Shangwu", "Changzhen", "Fenghuang Town", "Guangming St", "Guangming", "Science Park", "Loucun", "Honghuashan", "Gongming Square", "Heshuikou", "shutianpu", "Songgang Park", "Xitou", "Songgang"] },
    { name: 'Line 6 Branch', color: '#27b8b5', stations: ["Guangming", "Zhenmei", "Sun Yat-sen University", "SUAT"] },
    { name: 'Line 7', color: '#274c9d', stations: ["Xili Lake", "Xili", "Chaguang", "Zhuguang", "Longjing", "Taoyuancun", "Shenyun", "Antuo Hill", "Nonglin", "Chegongmiao", "Shangsha", "Shawei", "Shixia", "Huanggangcun", "Fumin", "Huanggang Checkpoint", "Fulin", "Chiwei", "Huaqiang South", "Huaqiang North", "Huaxin", "Huangmugang", "Bagualing", "Hongling North", "Sungang", "Honghu", "Tianbei", "Tai'an"] },
    { name: 'Line 8', color: '#bc6037', stations: ["Liantang", "Wutong Mountain South", "Shatoujiao", "Haishan", "Yantian Port West", "Shenwai Senior Campus", "Yantian Rd"] },
    { name: 'Line 9', color: '#8c7276', stations: ["Qianwan", "Menghai", "Yihai", "Litchi Orchards", "Nanyou West", "Nanyou", "Nanshan Book Mall", "Shenzhen University South", "Yuehaimen", "High-tech South", "Hongshuwan South", "Shenwan", "Shenzhen Bay Park", "Xiasha", "Chengongmiao", "Xiangmei", "Jingtian", "Meijing", "Xiameilin", "Meicun", "Shangmeilin", "Maling", "Yinhu", "Nigang", "Hongling North", "Yuanling", "Hongling", "Hongling South", "Ludancun", "Renmin South", "Xiangxicun", "Wenjin"] },
    { name: 'Line 10', color: '#ef7596', stations: ["Shuangyong Street", "Pinghu", "Hehua", "Huanancheng", "Mugu", "Shanglilang", "Liangmao Hill", "Gankeng", "Xuexiang", "Gangtou", "Huawei", "Beier Road", "Bantian North", "Wuhe", "Guangyayuan", "Nankeng", "Yabao", "Maling", "Donggualing", "Lianhuacun", "Gangxia North", "Gangxia", "Fumin", "Futian Checkpoint"] },
    { name: 'Line 11', color: '#712d4a', stations: ["Futian", "Chegongmiao", "Hongshuwan South", "Houhai", "Nanshan", "Qianhaiwan", "Bao'an", "Bihaiwan", "Airport", "Airport North", "Fuyong", "Qiaotou", "Tangwei", "Ma'an Hill", "Shajing", "Houting", "Songgang", "Bitou"] },
    { name: 'Line 12', color: '#a694b0', stations: ["Zuopaotai East", "Taiziwan", "Sea World", "Huaguoshan", "Sihai", "Nanyou", "Nanguang", "Nanshan", "Taoyuan", "Nantou Ancient City", "Zhongshan Park", "Tongle South", "Xin'an Park", "Lingzhi", "Shangchuan", "Liutang", "Bao'an Passenger Transport Terminal", "Baotian 1st Road", "Pingluan Hill", "Xixiang Taoyuan", "Zhongwu South", "Huangtian", "Xingwei", "Airport East", "Fuwei", "Huaide", "Fuyong", "Qiaotou West", "Fuhai West", "Shenzhen World", "Shenzhen World North", "Waterlands Resort South", "Waterlands Resort East", "Haoxiang", "Shahao", "Shajing Ancient Market", "Buchong", "Langxia", "Songgang"] },
    { name: 'Line 13', color: '#d48929', stations: ["Shenzhen Bay Checkpoint", "Talent Park", "Houhai", "Keyuan", "Yuehaimen", "Shenzhen University", "Hi-Tech Central", "Hi-Tech North", "Shigu", "Liuxiandong", "Baiwang", "Yingrenshi", "Luozu", "Shiyan", "Shangwu"] },
    { name: 'Line 14', color: '#eccd6c', stations: ["Gangxia North", "Huangmugang", "Luohu North", "Buji", "Shiyaling", "Liuyue North", "Silian", "Aobei", "Universiade", "Zhangbei", "Nanyue", "Baolong", "Jinlong", "Pingshanwei", "Pingshan Square", "Pingshan Center", "Kengzi", "Shatian"] },
    { name: 'Line 16', color: '#463f94', stations: ["Yuanshan Xikeng", "Anliang", "Fukeng", "Dakang", "Yuanshan", "Da'an", "Jixi", "Jinyuan", "Universiade", "3 14", "Universiade Center", "Longcheng Park", "Huanggekeng", "Yuyuan", "Huilongpu", "Shangjing", "Shengping", "Longyuan", "Shuanglong", "Xintangwei", "Longdong", "Baolong Tongle", "Pingshan", "Xinhe", "Liuhe", "Pingshanwei", "Pinghuan", "Dongjiang Column Memorial Hall", "Shabo", "Yanzihu", "Shijing", "Technology University", "Tianxin"] },
    { name: 'Line 20', color: '#9dd6dd', stations: ["Airport North", "Shenzhen World South", "Shenzhen World", "Shenzhen World North", "Convention & Exhibition City"] },
    { name: 'Pingshan SkyShuttle', color: '#b9b9b9', stations: ["Pingshan High-speed Railway Station", "Zhanqian Road East", "Culture Center", "Pingshan Center (SkyShuttle Line)", "Zhongxinguoji", "Bonded Area", "Yanziling", "Future City", "Natural History Museum West", "Longbei", "BYD North"] },
  ],
}
